config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # URLs de los recursos con vistas
  resources :notes
  resources :users
  resources :collections
  resources :friendships

  # URLs de CRUD para el admin
  namespace :admin do
    resources :notes
    resources :users
    resources :collections
    resources :friendships
  end

  root :to => "home#index"

  # as => "login" creates a login_path or login_url helper

  # Paginas estaticas sin nada mas
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#index', as: 'about'
  get 'admin', to: 'admin#index', as: 'admin'

  # Inicio y desconexion de sesion
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'login_post' 
  get 'logout', to: 'session#destroy', as: 'logout' 

  # Registro de usuarios
  get 'signup', to: 'users#new', as: 'signup'
  
  # URL que no sean resources ya que no tienen vistas
  get 'getNotifications', to: 'notifications#index', as: 'get_notifications'
  delete 'deleteNotification/:id', to: 'notifications#destroy', as: 'deleteNotification'

  # URL para compartir
  get 'sharing/:object', to: 'sharing#new', as: 'sharing_new'
  post 'sharing_create', to: 'sharing#create', as: 'sharing_create'
  get 'sharing_edit/:id', to: 'sharing#edit', as: 'sharing_edit'
  post 'sharing_update/:id', to: 'sharing#update', as: 'sharing_update'
  delete 'sharing_delete/:id', to: 'sharing#destroy', as: 'sharing_delete'
  delete 'unsharing/:id', to: 'sharing#unsharing', as: 'unsharing'

end

app/models/collection.rb
class Collection
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :name, type: String
  field :notes, type: Array, default: []
  has_many :sharings, as: :shareable, dependent: :destroy

  belongs_to :user

  validate :validate_title

  def name_valid
    'error_form' if errors[:base].any? 
  end

  private
  def validate_title
      if name.blank?
        errors.add(:base, "You must provide a title.")
      end
    end

end

app/controllers/admin/collections_controller.rb
module Admin
  class CollectionsController < CollectionsController
    skip_before_action :is_mine , only: [:destroy]
    skip_before_action :is_shared , only: [:show, :edit, :update]
    before_action :validate_admin

    def index
      @collections = Collection.all.map do |collection|
        notes = []
      
        collection.notes.each do |note_id|
          note = Note.find(note_id)
          notes << note
        end
        collection.assign_attributes(notes: notes)
        
        collection #es como si fuese un return
      end
    end

    def show
      @collection = Collection.find(params[:id])
    end

    protected
    def after_collection_create
      redirect_to admin_collections_path, notice: 'Collection was successfully created.' and return
    end

    def after_collection_update
      redirect_to admin_collections_path, notice: "Collection was successfully updated." and return
    end

    def after_collection_delete
      redirect_to admin_collections_path, notice: "Collection was successfully destroyed." and return 
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :validate_user
  before_action :is_mine , only: [:destroy]
  before_action :is_shared , only: [:show, :edit, :update]

  def is_mine
    @collection = Collection.find(params[:id])
    unless @collection.user_id == current_user.id
      redirect_to root_url
    end
  end

  def is_shared
    @collection = Collection.find(params[:id])
    sharing = Sharing.where(shareable_id: @collection.id).first
    @friend_sharing = @collection.sharings.any? && sharing&.shared_with&.include?(current_user.id.to_s)

    unless @collection.user_id == current_user.id || sharing&.shared_with&.include?(current_user.id.to_s)  
      redirect_to root_url
    end
  end
  
  def index
    @collections = (current_user.collections + current_user.shared_collections).map do |collection|
      notes = []
      
      collection.notes.each do |note_id|
        note = Note.find(note_id)
        notes << note if note.user_id == current_user.id
      end

      collection.assign_attributes(notes: notes)
      collection.assign_attributes(sharing: {
        shared: collection.sharings.any?,
        id: collection.sharings.first&.id,
        is_shared: !current_user.collections.include?(collection)
      })
      
      collection 
    end.sort_by { |collection| -collection.notes.size }
  end

  def show
    if @friend_sharing
      @collection = Collection.find(params[:id]).tap do |collection|
        notes = []

        collection.notes.each do |note_id|
          note = Note.find(note_id)
          notes << note
        end

        collection.assign_attributes(notes: notes)
      
        collection
      end
      
      @shared_id = Sharing.where(shareable_id: @collection.id).first.id

    else
      redirect_to collections_path
    end
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user

    if @collection.save
      after_collection_create
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update(collection_params)
      after_collection_update
    else
      @collection.reload
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @collection = Collection.find(params[:id])
      @collection.destroy
      after_collection_delete
  end

  protected
    def after_collection_create
      redirect_to collections_path, notice: 'Collection was successfully created.' and return
    end

    def after_collection_update
      if @friend_sharing
        redirect_to collection_path(@collection), notice: "Collection was successfully updated." and return
      else 
        redirect_to collections_path, notice: "Collection was successfully updated." and return
      end
    end

    def after_collection_delete
      redirect_to collections_path, notice: "Collection was successfully destroyed." and return 
    end

  private
    def collection_params
      params.require(:collection).permit(:name, :user, :notes)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<% is_admin = local_assigns[:is_admin] || false %>
<%= form_with(model: is_admin ? [:admin, collection] : collection) do |form| %>

  <div class="field mb-3">
    <%= form.label :name, 'Name of Collection', class:"form-label" %>
    <%= form.text_field :name, class: "form-control #{collection.name_valid}" %>
  </div>

  <div class="actions mb-3 text-center">
    <%= form.submit collection.new_record? ? 'New Collection' : 'Edit Collection', class: 'btn color_button_green fw-semibold' %>
  </div>
  
<% end %>

app/views/collections/edit.html.erb
<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <div class="d-flex justify-content-between align-items-center">
        <div class="text-center flex-grow-1 margin_text">
          <h2>Editing collection</h2>
        </div>
        <div>
        <%= link_to 'Go Back', collections_path, class: 'btn color_button_brown fw-semibold' %>
        </div>
      </div>

      <% if @collection.errors.any? %>
      <div id="error" class="text-danger mb-3 text-center">
        <% @collection.errors.full_messages.each do |message| %>
          <p class="pb-2 fw-semibold"><%= message %></p> 
        <% end %>     
      </div>       
    <% end %>

      <%= render 'form', collection: @collection %>
      
    </div>
  </div>
</div>

app/views/collections/index.html.erb
<% if alert || notice %>
    <div class="<%= alert ? 'alert alert-warning' : 'alert alert-success' %> alert-dismissible fade show mx-2 my-3" role="alert">
        <strong><%= alert ? 'Warning!' : 'Correct!' %></strong> <%= alert || notice %>
        <button id="botonCerrar" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" class="alert-close-button"></button>
    </div>

    <script>
        setTimeout(() => { document.getElementById('botonCerrar').click(); }, 3500);  
    </script>
<% end %>

<div class="ms-2 mt-1">
  <h1 id="namePage">Collections</h1>
  <%= link_to "New Collection", new_collection_path, class: "btn color_button_green fw-semibold mb-3" %>
</div>

<div class="row m-0">
  <% @collections.each_slice(4) do |collection_batch| %>
    <% collection_batch.each do |collection| %>
      <div class="col-md-3 mt-1 mb-3">
        <div class="card color_card box-shadow">
          <div class="card-body text-center">
            <h5 class="card-title"><%= collection.name %></h5>
            <% if collection.sharing[:is_shared] %>
              <small class="text-muted d-block text-center my-3 py-1">Shared with you <i class="bi bi-person-hearts"></i></small>
            <% else %>
              <%= link_to edit_collection_path(collection), class: "btn color_button_green fw-semibold mb-3 ms-2" do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>              
              <button onclick="createToastConfirm('collection',false,'<%= collection.id %>')" class="btn color_button_brown fw-semibold mb-3 ms-2">
                <i class="bi bi-trash-fill"></i>
              </button>
              
              <% if collection.sharing[:shared] %>
                <button onclick="shareContent('<%= collection.sharing[:id] %>', 'edit')" class="btn color_button_green fw-semibold mb-3 ms-2">
                  <i class="bi bi-share-fill"></i>
                </button>
              <% else %>
                <button onclick="shareContent('<%= collection.id %>', 'new')" class="btn color_button_green fw-semibold mb-3 ms-2">
                  <i class="bi bi-share-fill"></i>
                </button>
              <% end %>
            <% end %>
              <hr class="mt-0">
              <h6>Notes</h6>
              <% collection.notes.each do |note| %>
                <p class="card-text">
                  <%= link_to note.title, note_path(note), class: "btn color_button_notes btn-sm fw-semibold w-100" %>
                </p>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<button class="d-none" data-bs-toggle="modal" data-bs-target="#modalShare" id="buttonModalShare"></button>
<div class="modal fade" id="modalShare" tabindex="-1" aria-labelledby="modalShareLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title fs-5" id="modalShareLabel">Share</h3>
        <button id="modalClose" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="contentSharing">

      </div>
    </div>
  </div>
</div>

app/views/collections/new.html.erb
<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">

      <div class="d-flex justify-content-between align-items-center">
        <div class="text-center flex-grow-1 margin_text">
          <h2>New collection</h2>
        </div>
        <div>
        <%= link_to 'Go Back', collections_path, class: 'btn color_button_brown fw-semibold' %>
        </div>
      </div>

      <% if @collection.errors.any? %>
        <div id="error" class="text-danger mb-3 text-center">
          <% @collection.errors.full_messages.each do |message| %>
            <p class="pb-2 fw-semibold"><%= message %></p> 
          <% end %>     
        </div>       
      <% end %>

      <%= render 'form', collection: @collection %>
      
    </div>
  </div>
</div>

app/views/collections/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mx-2 my-3" role="alert">
      <strong>Correct!</strong> <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" id="botonCerrar"></button>
  </div>

  <script>
      setTimeout(() => { document.getElementById('botonCerrar').click(); }, 5000);
  </script>
<% end %>

<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="row">
        <div class="col-auto me-auto">
          <%= link_to edit_collection_path(@collection), class: 'btn color_button_green fw-semibold mb-3' do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
          <button onclick="createToastConfirm('unsharing', false, '<%= @shared_id %>')" class="btn color_button_brown fw-semibold mb-3 ms-2">
            <i class="bi bi-trash-fill"></i>
          </button>
        </div>
        <div class="col-auto">
          <%= link_to 'Go Back', friendships_path, class: 'btn color_button_brown fw-semibold' %>
        </div>
      </div>
      <div class="container border rounded color_card box-shadow mb-5">
        <div class="mt-3">
          <h2 class="text-center"><%= @collection.name.capitalize %></h2>
        </div>
        <h5 class="mt-2">Notes:</h5>
        <div class="row mb-5">
          <div class="col-12">
            <div class="list-group">
              <% @collection.notes.each do |note| %>
                <a href="<%= note_path(note) %>"  class="list-group-item list-group-item-action">
                  <%= note.title %>
                </a>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>