config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # URLs de los recursos con vistas
  resources :notes
  resources :users
  resources :collections
  resources :friendships

  # URLs de CRUD para el admin
  namespace :admin do
    resources :notes
    resources :users
    resources :collections
    resources :friendships
  end

  root :to => "home#index"

  # as => "login" creates a login_path or login_url helper

  # Paginas estaticas sin nada mas
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#index', as: 'about'
  get 'admin', to: 'admin#index', as: 'admin'

  # Inicio y desconexion de sesion
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'login_post' 
  get 'logout', to: 'session#destroy', as: 'logout' 

  # Registro de usuarios
  get 'signup', to: 'users#new', as: 'signup'
  
  # URL que no sean resources ya que no tienen vistas
  get 'getNotifications', to: 'notifications#index', as: 'get_notifications'
  delete 'deleteNotification/:id', to: 'notifications#destroy', as: 'deleteNotification'

  # URL para compartir
  get 'sharing/:object', to: 'sharing#new', as: 'sharing_new'
  post 'sharing_create', to: 'sharing#create', as: 'sharing_create'
  get 'sharing_edit/:id', to: 'sharing#edit', as: 'sharing_edit'
  post 'sharing_update/:id', to: 'sharing#update', as: 'sharing_update'
  delete 'sharing_delete/:id', to: 'sharing#destroy', as: 'sharing_delete'
  delete 'unsharing/:id', to: 'sharing#unsharing', as: 'unsharing'

end

app/models/note.rb
class Note
    include Mongoid::Document
    include Mongoid::Timestamps
  
    field :title, type: String
    field :content, type: Array
    has_many :sharings, as: :shareable, dependent: :destroy

    belongs_to :user

    validate :validate_content

    private
    def validate_content
        content_is_present = false
      
        if content.present?
          content.each do |content_item|
            content_hash = JSON.parse(content_item)
            unless content_hash['value'].blank?
              content_is_present = true
              break
            end
          end
        end
      
        if !content_is_present && title.blank?
          errors.add(:base, "You must provide at least one title or content.")
        end
      end
      
end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < NotesController
    skip_before_action :is_mine , only: [:destroy]
    skip_before_action :is_shared , only: [:show, :edit, :update]
    before_action :validate_admin
   
    def index
      @browser = Browser.new(request.user_agent)
      @notes = Note.all
    end
    
    protected
    def after_note_create
      redirect_to admin_notes_path, notice: 'Note was successfully created.'
    end

    def after_note_update
      redirect_to admin_notes_path, notice: 'Note was successfully updated.'
    end

    def after_note_delete
      redirect_to admin_notes_path, notice: 'Note was successfully destroyed.'
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :validate_user
  before_action :is_mine , only: [:destroy]
  before_action :is_shared , only: [:show, :edit, :update]

  def is_mine
    @note = Note.find(params[:id])
    unless @note.user_id == current_user.id
      redirect_to root_url
    end
  end

  def is_shared
    @note = Note.find(params[:id])
    sharing = Sharing.where(shareable_id: @note.id).first
    @friend_sharing = @note.sharings.any? && sharing&.shared_with&.include?(current_user.id.to_s)

    unless @note.user_id == current_user.id || sharing&.shared_with&.include?(current_user.id.to_s)
      redirect_to root_url
    end
  end
    
  def index
    @browser = Browser.new(request.user_agent)
    @notes = current_user.notes
  end
6
  def show
    @note = Note.find(params[:id])
    @shared = @note.sharings.any?
    @shared_id = @note.sharings.first&.id
    
    respond_to do |format|
      format.html
      format.json { render json: {
        note: @note,
        shared: @shared,
        shared_id: @shared_id
       } }
    end
  end

  def new
    @collections = get_collections_and_shared
    @collection_found = []
    @note = Note.new
  end

  def create
      @note = Note.new(title: note_params[:title])
      service = CollectionsNotesService.new(@note)
      @note.user = current_user
  
      if !params[:note][:content].blank?
        processed_content = params[:note][:content].map do |content_item|  
          case content_item[:type]
            when 'list'
              if !content_item[:value] == "" || !content_item[:value].all?(&:blank?)
                { type: 'list', value: content_item[:value].reject(&:blank?).join(';') }
              end
            when 'file'
              if !content_item[:value].blank?
                { type: 'file', value: handle_uploaded_file(content_item[:value]) }
              end
            when 'text'
              if !content_item[:value].blank?
                content_item       
              end 
          end
        end.compact
          
        @note.content = processed_content.map { |content_item| content_item.to_json }
      end

      if @note.save
        service.add_collections(note_params[:collection_ids])
        after_note_create
      else
        @collection_found = []
        @collections = get_collections_and_shared
        render :new, status: :unprocessable_entity
      end
  end

  def edit
    @note = Note.find(params[:id])

    @collections = get_collections_and_shared
    service = CollectionsNotesService.new(@note)
    @collection_found = service.get_collections(@collections)
  end
  
  def update
    @note = Note.find(params[:id])
    image_to_delete = params[:note][:images_to_delete]
    service = CollectionsNotesService.new(@note)
    browser = Browser.new(request.user_agent)
    image_to_update = {}

    @note.title = note_params[:title]

    if !params[:note][:content].blank?
      unless params[:note][:images_to_update].blank?
        image_to_update = params[:note][:images_to_update].each_with_object({}) do |image, hash|
          index = image[:index].to_i # Convertimos el index a int
          hash[index] = image[:value] # Asignamos el valor al index, es decir: {index => 'valor'}
        end
      end 

      processed_content = params[:note][:content].each_with_index.map do |content_item, index|
        case content_item[:type]
          when 'list'
            if !content_item[:value] == "" || !content_item[:value].all?(&:blank?)
              { type: 'list', value: content_item[:value].reject(&:blank?).join(';') }
            end
          when 'file'
            if !content_item[:value].blank?
              image = image_to_update[index]

              if !image.blank?
                { type: 'file', value: handle_uploaded_file(image) }
              else
                { type: 'file', value: handle_uploaded_file(content_item[:value]) }
              end
            end
          when 'text'
            if !content_item[:value].blank?
              content_item       
            end 
          end
      end.compact
  
      @note.content = processed_content.map { |content_item| content_item.to_json }

      if !image_to_delete.blank?
        @note.content.reject! do |content_string|
          item = JSON.parse(content_string)
          if item['type'] == 'file' && image_to_delete.include?(item['value'])
            deleteImage(item['value'])
            true 
          else
            false
          end
        end
      end
    end

    if @note.save
      service.update_collections(note_params[:collection_ids])
      after_note_update
    else
      @note.reload

      @collections = get_collections_and_shared
      service = CollectionsNotesService.new(@note)
      @collection_found = service.get_collections(@collections)

      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @note = Note.find(params[:id])
      
    service = CollectionsNotesService.new(@note)
    service.delete_collections
  
    unless @note.content.blank?
      @note.content.each do |content_string|
        content_item = JSON.parse(content_string)
        
        if content_item['type'] == 'file'
          deleteImage(content_item['value'])
        end
      end
    end

    @note.destroy
    after_note_delete
  end

  protected
    def after_note_create
      if browser.device.mobile?
        redirect_to @note, notice: 'Note was successfully created.' and return
      else
        redirect_to notes_path(number: @note.id), notice: 'Note was successfully created.'
      end
    end

    def after_note_update
      if @friend_sharing
        redirect_to @note, notice: 'Note was successfully updated.' and return
      else
        if browser.device.mobile?
          redirect_to @note, notice: 'Note was successfully updated.' and return
        else
          redirect_to notes_path(number: @note.id), notice: 'Note was successfully updated.'
        end
      end
    end

    def after_note_delete
      redirect_to notes_path, notice: 'Note was successfully destroyed.' 
    end

  private
    def note_params
      params.require(:note).permit(
        :title,
        :user,
        content: [:type,{value: []},:value],
        images_to_update: [:index,:value],
        images_to_delete: [],
        collection_ids: []
      )
    end

    def deleteImage(image_path)
      file_path = Rails.root.join('public', 'uploads', image_path.split('/').last) 
      File.delete(file_path) if File.exist?(file_path)
    end

    def handle_uploaded_file(uploaded_file)
      if uploaded_file.blank?
        return ""
      else     
          if uploaded_file.is_a?(String)
            return uploaded_file
          else
            file_name = SecureRandom.uuid + File.extname(uploaded_file.original_filename)
            file_path = Rails.root.join('public', 'uploads', file_name)

            File.open(file_path, 'wb') do |file|
              file.write(uploaded_file.read)
            end

            return "/uploads/#{file_name}"
          end
      end
    end

    def get_collections_and_shared
      collections = current_user.collections
      Rails.logger.debug "Collections: #{collections}"
      collection_shared = current_user.shared_collections
      Rails.logger.debug "Collections Shared: #{collection_shared}"
      collections_and_shared = (collections + collection_shared).uniq
      Rails.logger.debug "Collections and Shared: #{collections_and_shared}"
      return collections_and_shared
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<% is_admin = local_assigns[:is_admin] || false %>
<%= form_with model: (is_admin ? [:admin, note] : note), local: true, html: { multipart: true } do |form| %>

    <% if !collections.blank? %>
      <%= label_tag 'Collections', 'Collections of the note', class: 'form-label' %><br>
      <div class="field mb-3">
        <input class="form-control" id="inputContent" type="text" placeholder="Search...">
        <ul class="list-group search_max mt-1" id="listContent">
        <% collections.each do |collection| %>
          <li class="list-group-item">
            <%= check_box_tag 'note[collection_ids][]', collection.id, @collection_found.include?(collection.id.to_s) %>
            <%= collection.name %><br>
          </li>
        <% end %>
      </div>
    <% end %>
  
    <div class="field mb-3">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control', rows: '3' %>
    </div>
  
    <% if note.content.present? %>
      <% note.content.each_with_index do |content_string, index| %>
        <% item = JSON.parse(content_string) %>
        <% if item['type'] == 'text' %>
          <%= render 'notes/partials/text_field', index: index, item: item %>
        <% elsif item['type'] == 'list' %>
          <%= render 'notes/partials/list_field', index: index, item: item %>
        <% elsif item['type'] == 'file' %>
          <%= render 'notes/partials/file_field', index: index, item: item %>
        <% end %>
      <% end %>
    <% end %>

    <div id="contentContainer">
        <!-- Los campos se añadirán aquí -->
    </div>
  
    <div class="actions mb-3 text-center">
      <%= form.submit note.new_record? ? 'Create Note' : 'Edit Note', class: 'btn color_button_green fw-semibold' %>
    </div>
  
<% end %>
  
  

app/views/notes/edit.html.erb
<!-- app/views/notes/edit.html.erb -->
<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">

    <div class="d-flex justify-content-between align-items-center">
      <div class="text-center flex-grow-1 margin_text">
        <h2>Edit Note</h2>
      </div>
      <div>
        <%= link_to 'Go Back', notes_path, class: 'btn color_button_brown fw-semibold' %>
      </div>
    </div>
    
      <div id="error" class="text-danger mb-3 text-center">
        <% if @note.errors.any? %>
          <% @note.errors.full_messages.each do |message| %>
            <p class="fw-semibold"><%= message %></p> 
          <% end %>            
        <% end %>
      </div>

      <div id="fixed-buttons-container" style="position: static;">
        <div class="field mb-3 text-center">
          <button type="button" onclick="addContentType('text')" class="btn color_button_green fw-semibold">Add Text</button>
          <button type="button" onclick="addContentType('list')" class="btn color_button_green fw-semibold">Add List</button>
          <button type="button" onclick="addContentType('file')" class="btn color_button_green fw-semibold">Add Image</button>
        </div>
      </div>

      <%= render 'form', note: @note, collections: @collections %>

    </div>
  </div>
</div>

<%= javascript_include_tag 'fixed' %>

app/views/notes/index.html.erb
<% if alert || notice %>
    <div class="<%= alert ? 'alert alert-warning' : 'alert alert-success' %> alert-dismissible fade show mx-2 my-3" role="alert">
        <strong><%= alert ? 'Warning!' : 'Correct!' %></strong> <%= alert || notice %>
        <button id="botonCerrar" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" class="alert-close-button"></button>
    </div>

    <script>
        setTimeout(() => { document.getElementById('botonCerrar').click(); }, 3500);
    </script>
<% end %>

<h1 class="ms-2" id="namePage">Notes</h1>

<div class="row m-0 p-0 mb-4">
    <div class="col-12 col-md-3">
        <ul class="list-group">
            <li class="decoration-none"> <%= link_to 'New Note', new_note_path, class:'btn color_button_green fw-semibold w-100 mb-2' %></li>
            <% @notes.each do |note| %>
                <% if @browser.device.mobile? %>
                    <li class="list-group-item color_card">
                        <% if note.title.blank? %>
                            <a href="<%= note_path(note) %>" class="btn p-2 w-100"></a>
                        <% else %>
                            <a href="<%= note_path(note) %>" class="btn p-0 w-100"><%= note.title %></a>
                        <% end %>
                    </li>
                <% else %>
                    <li class="list-group-item listSelected color_card" onclick="showNote('<%= note.id %>')">
                        <% if note.title.blank? %>
                            <span class="p-2"></span>
                        <% else %>
                            <%= note.title %>
                        <% end %>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
    <div class="col-12 col-md-9 d-none" id="fatherContent">
        <div class="card color_card box-shadow">
            <div class="card-body" id="content">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalShare" tabindex="-1" aria-labelledby="modalShareLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title fs-5" id="modalShareLabel">Share</h3>
        <button id="modalClose" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="contentSharing">

      </div>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">

    <div class="d-flex justify-content-between align-items-center">
      <div class="text-center flex-grow-1 margin_text">
        <h2>Create Note</h2>
      </div>
      <div>
        <%= link_to 'Go Back', notes_path, class: 'btn color_button_brown fw-semibold' %>
      </div>
    </div>

      <% if @note.errors.any? %>
        <div id="error" class="text-danger mb-3 text-center">
          <% @note.errors.full_messages.each do |message| %>
            <p class="pb-2 fw-semibold"><%= message %></p> 
          <% end %>     
        </div>       
      <% end %>
      
      <div id="fixed-buttons-container">
        <div class="field mb-2 text-center">
          <button type="button" onclick="addContentType('text')" class="btn color_button_green fw-semibold">Add Text</button>
          <button type="button" onclick="addContentType('list')" class="btn color_button_green fw-semibold">Add List</button>
          <button type="button" onclick="addContentType('file')" class="btn color_button_green fw-semibold">Add Image</button>
        </div>
      </div>

      <%= render 'form', note: @note, collections: @collections %>

    </div>
  </div>
</div>

<%= javascript_include_tag 'fixed' %>

app/views/notes/show.html.erb
<% if alert || notice %>
    <div class="<%= alert ? 'alert alert-warning' : 'alert alert-success' %> alert-dismissible fade show mx-2 my-3" role="alert">
        <strong><%= alert ? 'Warning!' : 'Correct!' %></strong> <%= alert || notice %>
        <button id="botonCerrar" type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" class="alert-close-button"></button>
    </div>

    <script>
        setTimeout(() => { document.getElementById('botonCerrar').click(); }, 3500);  
    </script>
<% end %>

<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="row">
        <div class="col-auto me-auto">
          <%= link_to edit_note_path(@note), class: 'btn color_button_green fw-semibold mb-3' do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
          <% unless @friend_sharing %>
            <button onclick="createToastConfirm('note', false, '<%= @note.id %>')" class="btn color_button_brown fw-semibold mb-3 ms-2">
              <i class="bi bi-trash-fill"></i>
            </button>
            <% if @shared %>
              <button onclick="shareContent('<%= @shared_id %>', 'edit')" class="btn color_button_green fw-semibold mb-3 ms-2">
                <i class="bi bi-share-fill"></i>
              </button>
            <% else %>
              <button onclick="shareContent('<%= @note.id %>', 'new')" class="btn color_button_green fw-semibold mb-3 ms-2">
                <i class="bi bi-share-fill"></i>
              </button>
            <% end %>
          <% else %>
            <button onclick="createToastConfirm('unsharing', false, '<%= @shared_id %>')" class="btn color_button_brown fw-semibold mb-3 ms-2">
              <i class="bi bi-trash-fill"></i>
            </button>
          <% end %>
        </div>
        <div class="col-auto">
          <% if @friend_sharing %>
            <%= link_to 'Go Back', friendships_path, class: 'btn color_button_brown fw-semibold' %>
          <% else %>
            <%= link_to 'Go Back', notes_path, class: 'btn color_button_brown fw-semibold' %>
          <% end %>
        </div>
      </div>
      <div class="container border rounded color_card box-shadow mb-5">
        <div class="text-center">
          <h1 class="d-none" id="namePage">Notes</h1>
          <p class="d-none" id="id_note">show;<%= @note.id %></p>
          <h3 class="mt-2"><%= @note.title %></h3>
        </div>
        <div class="mb-5">
          <% if @note.content.present? %>
            <% @note.content.each do |content_string| %>
              <% item = JSON.parse(content_string)%>
              <% if item['type'] == 'text' %>
                <p><%= item['value'] %></p>
              <% elsif item['type'] == 'list' %>
                <ul>
                  <% item['value'].split(';').each do |list_item| %>
                    <li><%= list_item %></li>
                  <% end %>
                </ul>
              <% elsif item['type'] == 'file' %>
              <div class="card-group mb-3">
                <div class="card color_card">
                  <div class="card-body text-center">
                    <img src=<%= item['value'] %> style="width: 150px; height: 150px;">
                  </div>
                </div>
              </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<button class="d-none" data-bs-toggle="modal" data-bs-target="#modalShare" id="buttonModalShare"></button>
<div class="modal fade" id="modalShare" tabindex="-1" aria-labelledby="modalShareLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title fs-5" id="modalShareLabel">Share</h3>
        <button id="modalClose" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="contentSharing">

      </div>
    </div>
  </div>
</div>