config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # URLs de los recursos con vistas
  resources :notes
  resources :users
  resources :collections
  resources :friendships

  # URLs de CRUD para el admin
  namespace :admin do
    resources :notes
    resources :users
    resources :collections
    resources :friendships
  end

  root :to => "home#index"

  # as => "login" creates a login_path or login_url helper

  # Paginas estaticas sin nada mas
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#index', as: 'about'
  get 'admin', to: 'admin#index', as: 'admin'

  # Inicio y desconexion de sesion
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'login_post' 
  get 'logout', to: 'session#destroy', as: 'logout' 

  # Registro de usuarios
  get 'signup', to: 'users#new', as: 'signup'
  
  # URL que no sean resources ya que no tienen vistas
  get 'getNotifications', to: 'notifications#index', as: 'get_notifications'
  delete 'deleteNotification/:id', to: 'notifications#destroy', as: 'deleteNotification'

  # URL para compartir
  get 'sharing/:object', to: 'sharing#new', as: 'sharing_new'
  post 'sharing_create', to: 'sharing#create', as: 'sharing_create'
  get 'sharing_edit/:id', to: 'sharing#edit', as: 'sharing_edit'
  post 'sharing_update/:id', to: 'sharing#update', as: 'sharing_update'
  delete 'sharing_delete/:id', to: 'sharing#destroy', as: 'sharing_delete'
  delete 'unsharing/:id', to: 'sharing#unsharing', as: 'unsharing'

end

app/views/admin/index.html.erb
<h3 class="d-block d-md-none text-center pt-2">System management</h3>
<div class="row m-0">       
    <div id="columnaOpciones" class="col-4 col-md-3">
        <h2 class="pt-2 text-center d-none d-md-block">Welcome!</h2>
        <div class="border rounded p-2 color_card box-shadow">
            <p><b>User:</b> <%= current_user.name&.capitalize %></p>
            <p><b>Day:</b> <%= Date.today.strftime("%d/%m/") %><span class="d-none d-md-inline"><%= Date.today.year %></span><span class="d-inline d-md-none"><%= Date.today.strftime("%y") %></span></p>
            <p><b>Remember:</b> <label class="d-block d-md-inline">Always smile.</label></p>
            <p class="text-center"><b>Have a nice day</b></p>
            <p class="text-center">ʕ•ᴥ•ʔ</p>
        </div>
    </div>

    <div id="columnaContenido" class="col-8 col-md-9">
        <h2 id="tituloZona" class="text-center pt-2 d-none d-md-block">System management</h2>
        <div id="tarjetasZona" class="row">
            <div class="col-md-6 col-lg-6 mb-4">
                <div class="card h-100 color_card box-shadow">
                    <div class="card-body text-center">
                        <img class="card-img-top imgAdmin" alt="administradores" src="<%= asset_path 'users.png' %>">
                        <h5 class="card-text m-3"><a href="<%= admin_users_path %>">Users</a></h5>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 mb-4">
                <div class="card h-100 color_card box-shadow">
                    <div class="card-body text-center">
                        <img class="card-img-top imgAdmin" alt="animales" src="<%= asset_path 'collections.png' %>">
                        <h5 class="card-text m-3"><a href="<%= admin_collections_path %>">Collections</a></h5>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 mb-4">
                <div class="card h-100 color_card box-shadow">
                    <div class="card-body text-center">
                        <img class="card-img-top imgAdmin" alt="clientes" src="<%= asset_path 'notes.png' %>">
                        <h5 class="card-text m-3"><a href="<%= admin_notes_path %>">Notes</a></h5>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 mb-4">
                <div class="card h-100 color_card box-shadow">
                    <div class="card-body text-center">
                        <img class="card-img-top imgAdmin" alt="citas" src="<%= asset_path 'relationships.png' %>">
                        <h5 class="card-text m-3"><a href="<%= admin_friendships_path %>">Friendships</a></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>