config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # URLs de los recursos con vistas
  resources :notes
  resources :users
  resources :collections
  resources :friendships

  # URLs de CRUD para el admin
  namespace :admin do
    resources :notes
    resources :users
    resources :collections
    resources :friendships
  end

  root :to => "home#index"

  # as => "login" creates a login_path or login_url helper

  # Paginas estaticas sin nada mas
  get 'home', to: 'home#index', as: 'home'
  get 'about', to: 'about#index', as: 'about'
  get 'admin', to: 'admin#index', as: 'admin'

  # Inicio y desconexion de sesion
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'login_post' 
  get 'logout', to: 'session#destroy', as: 'logout' 

  # Registro de usuarios
  get 'signup', to: 'users#new', as: 'signup'
  
  # URL que no sean resources ya que no tienen vistas
  get 'getNotifications', to: 'notifications#index', as: 'get_notifications'
  delete 'deleteNotification/:id', to: 'notifications#destroy', as: 'deleteNotification'

  # URL para compartir
  get 'sharing/:object', to: 'sharing#new', as: 'sharing_new'
  post 'sharing_create', to: 'sharing#create', as: 'sharing_create'
  get 'sharing_edit/:id', to: 'sharing#edit', as: 'sharing_edit'
  post 'sharing_update/:id', to: 'sharing#update', as: 'sharing_update'
  delete 'sharing_delete/:id', to: 'sharing#destroy', as: 'sharing_delete'
  delete 'unsharing/:id', to: 'sharing#unsharing', as: 'unsharing'

end

app/models/collection.rb
class Collection
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :name, type: String
  field :notes, type: Array, default: []
  has_many :sharings, as: :shareable, dependent: :destroy

  belongs_to :user

  validate :validate_title

  def name_valid
    'error_form' if errors[:base].any? 
  end

  private
  def validate_title
      if name.blank?
        errors.add(:base, "You must provide a title.")
      end
    end

end

app/controllers/admin/collections_controller.rb
module Admin
  class CollectionsController < CollectionsController
    skip_before_action :is_mine , only: [:destroy]
    skip_before_action :is_shared , only: [:show, :edit, :update]
    before_action :validate_admin

    def index
      @collections = Collection.all.map do |collection|
        notes = []
      
        collection.notes.each do |note_id|
          note = Note.find(note_id)
          notes << note
        end
        collection.assign_attributes(notes: notes)
        
        collection #es como si fuese un return
      end
    end

    def show
      @collection = Collection.find(params[:id])
    end

    protected
    def after_collection_create
      redirect_to admin_collections_path, notice: 'Collection was successfully created.' and return
    end

    def after_collection_update
      redirect_to admin_collections_path, notice: "Collection was successfully updated." and return
    end

    def after_collection_delete
      redirect_to admin_collections_path, notice: "Collection was successfully destroyed." and return 
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :validate_user
  before_action :is_mine , only: [:destroy]
  before_action :is_shared , only: [:show, :edit, :update]

  def is_mine
    @collection = Collection.find(params[:id])
    unless @collection.user_id == current_user.id
      redirect_to root_url
    end
  end

  def is_shared
    @collection = Collection.find(params[:id])
    sharing = Sharing.where(shareable_id: @collection.id).first
    @friend_sharing = @collection.sharings.any? && sharing&.shared_with&.include?(current_user.id.to_s)

    unless @collection.user_id == current_user.id || sharing&.shared_with&.include?(current_user.id.to_s)  
      redirect_to root_url
    end
  end
  
  def index
    @collections = (current_user.collections + current_user.shared_collections).map do |collection|
      notes = []
      
      collection.notes.each do |note_id|
        note = Note.find(note_id)
        notes << note if note.user_id == current_user.id
      end

      collection.assign_attributes(notes: notes)
      collection.assign_attributes(sharing: {
        shared: collection.sharings.any?,
        id: collection.sharings.first&.id,
        is_shared: !current_user.collections.include?(collection)
      })
      
      collection 
    end.sort_by { |collection| -collection.notes.size }
  end

  def show
    if @friend_sharing
      @collection = Collection.find(params[:id]).tap do |collection|
        notes = []

        collection.notes.each do |note_id|
          note = Note.find(note_id)
          notes << note
        end

        collection.assign_attributes(notes: notes)
      
        collection
      end
      
      @shared_id = Sharing.where(shareable_id: @collection.id).first.id

    else
      redirect_to collections_path
    end
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user

    if @collection.save
      after_collection_create
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update(collection_params)
      after_collection_update
    else
      @collection.reload
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
      @collection = Collection.find(params[:id])
      @collection.destroy
      after_collection_delete
  end

  protected
    def after_collection_create
      redirect_to collections_path, notice: 'Collection was successfully created.' and return
    end

    def after_collection_update
      if @friend_sharing
        redirect_to collection_path(@collection), notice: "Collection was successfully updated." and return
      else 
        redirect_to collections_path, notice: "Collection was successfully updated." and return
      end
    end

    def after_collection_delete
      redirect_to collections_path, notice: "Collection was successfully destroyed." and return 
    end

  private
    def collection_params
      params.require(:collection).permit(:name, :user, :notes)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/admin/collections/edit.html.erb
<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="d-flex justify-content-between align-items-center">
        <div class="text-center flex-grow-1 margin_text">
          <h2>Edit Collection</h2>
        </div>
        <div>
          <%= link_to 'Go Back', admin_collections_path, class: 'btn color_button_brown fw-semibold' %>
        </div>
      </div>

      <div id="error" class="text-danger mb-3 text-center">
        <% if @collection.errors.any? %>
          <% @collection.errors.full_messages.each do |message| %>
            <p class="fw-semibold"><%= message %></p> 
          <% end %>            
        <% end %>
      </div>

      <%= render 'collections/form', collection: @collection, is_admin: true %>

    </div>
  </div>
</div>

app/views/admin/collections/index.html.erb
<h1 class="ms-2">Collections</h1>

<% if notice %>
    <div class="alert alert-success alert-dismissible fade show mx-2 my-3" role="alert">
        <strong>Correct!</strong> <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" id="botonCerrar"></button>
    </div>

    <script>
        setTimeout(() => { document.getElementById('botonCerrar').click(); }, 3500);       
    </script>
<% end %>

<div class="row m-0 p-0">
  <div class="col-12">
    <div class="d-flex justify-content-between align-items-center">
      <div class="flex-grow-1">
        <%= link_to 'New Collection', new_admin_collection_path, class: 'btn color_button_green fw-semibold mb-3' %>
      </div>
      <div>
        <%= link_to 'Go Back', admin_path, class: 'btn color_button_brown fw-semibold mb-3' %>
      </div>
    </div>

    <input id="tableContentTD" type="text" class="form-control mb-3" placeholder="Search by Title...">
    <div class="table-responsive">
      <table class="table color_card border rounded box-shadow">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Notes</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody id="contentTable">
          <% @collections.each do |collection| %>
            <tr>
              <td id="tdSearch"><%= collection.name %></td>
              <td><%= collection.notes&.length || 0 %> <label class="d-none d-md-inline">associated.</label></td>
              <td>
                <%= link_to admin_collection_path(collection), class: 'btn color_button_brown fw-semibold mx-1 mt-1 my-mt-0' do %>
                  <i class="bi bi-eye-fill"></i>
                <% end %>
                <%= link_to edit_admin_collection_path(collection), class: 'btn color_button_green fw-semibold mx-1 mt-1 my-mt-0' do %>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
                <button onclick="createToastConfirm('collection',true,'<%= collection.id %>')" class="btn color_button_brown fw-semibold mx-1 mt-1 my-mt-0">
                  <i class="bi bi-trash-fill"></i>
                </button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/collections/new.html.erb
<div class="container mt-2">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="d-flex justify-content-between align-items-center">
        <div class="text-center flex-grow-1 margin_text">
          <h2>New Collection</h2>
        </div>
        <div>
          <%= link_to 'Go Back', admin_collections_path, class: 'btn color_button_brown fw-semibold' %>
        </div>
      </div>

      <div id="error" class="text-danger mb-3 text-center">
        <% if @collection.errors.any? %>
          <% @collection.errors.full_messages.each do |message| %>
            <p class="fw-semibold"><%= message %></p> 
          <% end %>            
        <% end %>
      </div>

      <%= render 'collections/form', collection: @collection, is_admin: true %>

    </div>
  </div>
</div>

app/views/admin/collections/show.html.erb
<div class="container mt-2">
  <div class="row justify-content-center">
    <h3 class="text-center mb-3">Collection</h3>
    <div class="col-md-8">
      <div class="row">
        <div class="col-auto me-auto">
          <%= link_to edit_admin_collection_path(@collection), class: 'btn color_button_green fw-semibold mb-3' do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
          <button onclick="createToastConfirm('collection', true,'<%= @collection.id %>')" class="btn color_button_brown fw-semibold mb-3 ms-2">
            <i class="bi bi-trash-fill"></i>
          </button>
        </div>
        <div class="col-auto">
          <%= link_to 'Go Back', admin_collections_path, class: 'btn color_button_brown fw-semibold' %>
        </div>
      </div>
      <div class="container border rounded color_card box-shadow mb-5">
        <div class="form-group mt-3">
          <label class="fw-semibold">Title:</label>
          <span class="form-control underline" disabled><%= @collection.name.capitalize %></span>
        </div>
        <div class="form-group">
          <label class="fw-semibold">Notes:</label>
          <span class="form-control underline" disabled><%= "#{@collection.notes&.length || 0} associated." %></span>
        </div>
        <div class="form-group mt-3">
          <label class="fw-semibold">Owner:</label>
          <span class="form-control underline" disabled><%= @collection.user.email %></span>
        </div>
        <div class="form-group">
          <label class="fw-semibold">Created At:</label>
          <span class="form-control underline" disabled><%= @collection.created_at %></span>
        </div>
        <div class="form-group">
          <label class="fw-semibold">Updated At:</label>
          <span class="form-control underline" disabled><%= @collection.updated_at %></span>
        </div>
      </div>
    </div>
  </div>
</div>